language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
install:
  - pip install -e . --use-mirrors
  - pip install pep8 --use-mirrors
script:
  - pep8 --repeat --show-source --exclude=.venv,.tox,dist,doc,build,*.egg .
  - python setup.py test
services:
  - redis-server
matrix:
  include:
    - python: "2.7"
    - python: "3.3"
